// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Hono Server
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import customRoutes from './custom-routes'
import { createToolsHandlers } from '@shogo-ai/sdk/tools/server'

const app = new Hono()

// CORS — manual middleware so the wildcard always propagates
app.use('*', async (c, next) => {
  c.res.headers.set('Access-Control-Allow-Origin', '*')
  c.res.headers.set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS')
  c.res.headers.set('Access-Control-Allow-Headers', 'Content-Type,Authorization')
  if (c.req.method === 'OPTIONS') return c.text('', 204)
  await next()
})

// Health check endpoint
app.get('/health', (c) => c.json({ ok: true, timestamp: new Date().toISOString() }))

// Auth middleware — runs for ALL /api/* routes
import jwt from 'jsonwebtoken'
const JWT_SECRET = process.env.JWT_SECRET || 'pakbooster2026secret'

app.use('*', async (c, next) => {
  const auth = c.req.header('Authorization')
  if (auth?.startsWith('Bearer ')) {
    try {
      const decoded = jwt.verify(auth.slice(7), JWT_SECRET) as any
      c.set('auth', { userId: decoded.userId, tunnelAuthenticated: true })
      c.set('userId', decoded.userId)
      c.set('isAdmin', decoded.isAdmin || false)
    } catch {}
  }
  await next()
})

// Custom API routes (handles all CRUD + business logic)
app.route('/api', customRoutes)

// Installed-integration tools proxy → forwards to the agent runtime
// using RUNTIME_AUTH_SECRET + RUNTIME_PORT (auto-detected from env).
const tools = createToolsHandlers({})
app.post('/api/tools/execute', (c) => tools.execute(c.req.raw))
app.get('/api/tools/schemas', (c) => tools.list(c.req.raw))

// Serve static files in production
app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
console.log(`🚀 Server running on http://localhost:${port}`)

Bun.serve({ port, fetch: app.fetch })
